CREATE TABLE users
(
    userid            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name        VARCHAR(50),
    last_name         VARCHAR(50),
    phone_number      VARCHAR(20),
    date_of_birth     date,
    address           VARCHAR(255),
    city              VARCHAR(100),
    country           VARCHAR(100),
    profile_image_url VARCHAR(255),
    bio               TEXT,
    CONSTRAINT pk_users PRIMARY KEY (userid)
);
