CREATE TABLE accounts
(
    accountid           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    userid              INTEGER,
    username            VARCHAR(50)                              NOT NULL,
    password            VARCHAR(255)                             NOT NULL,
    is_active           BOOLEAN                     DEFAULT TRUE,
    is_verified         BOOLEAN                     DEFAULT FALSE,
    created_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    last_login          TIMESTAMP WITHOUT TIME ZONE,
    verification_token  VARCHAR(255),
    reset_token         VARCHAR(255),
    reset_token_expires TIMESTAMP WITHOUT TIME ZONE,
    role                VARCHAR(255),
    CONSTRAINT pk_accounts PRIMARY KEY (accountid)
);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_userid UNIQUE (userid);

ALTER TABLE accounts
    ADD CONSTRAINT FK_ACCOUNTS_ON_USERID FOREIGN KEY (userid) REFERENCES users (userid);
alter table accounts
add column     email             VARCHAR(100)               not null ;
