spring:
  security:
    user:
      name: user
      password: password

  application:
    name: TestingServerApi
  datasource:
    url: jdbc:postgresql://localhost:5432/database_auth_server
    username: postgres
    password: 30102001
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  header: Authorization
  secret: ==================springboot=jwt=example========================
server:
  port: 8080
