spring:
  application:
    name: TestingServerApi
  datasource:
    url: jdbc:postgresql://localhost:5432/api_server_db
    username: postgres
    password: 301022001
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop