spring:
  application:
    name: TestingServerApi
  datasource:
    url: jdbc:postgresql://localhost:5432/api_server_db
    username: postgres
    password: 30102001
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  header: Authorization
  secret: ==================springboot=jwt=example========================